# Generated by Django 5.1.6 on 2025-02-10 03:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('part_number', models.CharField(help_text='Codigo da peça.', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Nome da peça.', max_length=30)),
                ('details', models.TextField(blank=True, help_text='Detalhes ou descrição da peça.', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Preço da peça.', max_digits=10)),
                ('quantity', models.IntegerField(default=1, help_text='Quantidade disponível em estoque.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização.')),
                ('car_models', models.ManyToManyField(blank=True, help_text='Modelos de carro associados à peça.', related_name='parts', to='car.car')),
            ],
        ),
    ]
