# Generated by Django 5.1.6 on 2025-02-10 03:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nome do carro.', max_length=15)),
                ('manufacturer', models.CharField(help_text='Nome do fabricante.', max_length=20)),
                ('year', models.IntegerField(default=0, help_text='Ano do veiculo.')),
            ],
        ),
    ]
